---
name: Devel-FindBlessedRefs
version: 1.1.2
author:
  - 'Paul Miller <paul@cpan.org>'
abstract: find all refs blessed under a package
license: lgpl
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  version: 0
build_requires:
  ExtUtils::CBuilder: 0
provides:
  Devel::FindBlessedRefs:
    file: FindBlessedRefs.pm
    version: 1.1.2
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
