--- #YAML:1.0
name:               Devel-FindBlessedRefs
version:            1.252
abstract:           ~
author:
    - Paul Miller <jettero@cpan.org>
license:            lgpl2
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:  5.008
resources:
    repository:  http://github.com/jettero/devel--findblessedrefs/tree
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - blessed
    - refs
